; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[block_layout_ou][download][type] = ""
projects[block_layout_ou][download][url] = ""
projects[block_layout_ou][type] = "module"
projects[block_layout_ou][subdir] = "custom/ou_features"
projects[block_layout_ou][version] = "1.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[brand_ou][download][type] = ""
projects[brand_ou][download][url] = ""
projects[brand_ou][type] = "module"
projects[brand_ou][subdir] = "custom/ou_features"
projects[brand_ou][version] = "1.0-beta2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[brand_ou_basic_page_extensions][download][type] = ""
projects[brand_ou_basic_page_extensions][download][url] = ""
projects[brand_ou_basic_page_extensions][type] = "module"
projects[brand_ou_basic_page_extensions][subdir] = "custom/ou_features"
projects[brand_ou_basic_page_extensions][version] = "1.1"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.9"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.16"

projects[ckeditor_link][subdir] = "contrib"
projects[ckeditor_link][version] = "2.3"

projects[content_access][subdir] = "contrib"
projects[content_access][version] = "1.2-beta2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[core_internet_ou][download][type] = ""
projects[core_internet_ou][download][url] = ""
projects[core_internet_ou][type] = "module"
projects[core_internet_ou][subdir] = "custom/ou_features"
projects[core_internet_ou][version] = "1.12"

projects[date][subdir] = "contrib"
projects[date][version] = "2.8"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[easy_breadcrumb][subdir] = "contrib"
projects[easy_breadcrumb][version] = "2.12"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[employment_config][download][type] = ""
projects[employment_config][download][url] = ""
projects[employment_config][type] = "module"
projects[employment_config][version] = "1.0"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.6"

projects[features_extra][subdir] = "custom/custom/contrib_dev_modules"
projects[features_extra][version] = "1.0-alpha1+19-dev"

projects[features][subdir] = "contrib"
projects[features][version] = "2.2"

projects[features_override][subdir] = "contrib"
projects[features_override][version] = "2.0-rc2"

projects[media][subdir] = "contrib"
projects[media][version] = "1.4"

projects[filefield_sources][subdir] = "contrib"
projects[filefield_sources][version] = "1.9"

projects[ftools][subdir] = "contrib"
projects[ftools][version] = "1.6"

projects[globalredirect][subdir] = "contrib"
projects[globalredirect][version] = "1.5"

projects[htmlpurifier][subdir] = "contrib"
projects[htmlpurifier][version] = "1.0"

projects[imce][version] = "1.9"

projects[imce_filefield][version] = "1.1"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.2"

projects[oembed][subdir] = "contrib"
projects[oembed][version] = "0.1-beta3"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[media_player_ou][download][type] = ""
projects[media_player_ou][download][url] = ""
projects[media_player_ou][type] = "module"
projects[media_player_ou][subdir] = "custom/ou_features"
projects[media_player_ou][version] = "1.0-beta1"

projects[memcache_storage][subdir] = "contrib"
projects[memcache_storage][version] = "1.4"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.4"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.0-rc2"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0-alpha2"

projects[references][subdir] = "contrib"
projects[references][version] = "2.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_ck_editor_defaults][download][type] = ""
projects[ou_ck_editor_defaults][download][url] = ""
projects[ou_ck_editor_defaults][type] = "module"
projects[ou_ck_editor_defaults][subdir] = "custom/ou_features"
projects[ou_ck_editor_defaults][version] = "1.11"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[Open University][download][type] = ""
projects[Open University][download][url] = ""
projects[Open University][type] = "module"
projects[Open University][subdir] = "custom/custom"
projects[Open University][version] = "7.3.0.3"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pathauto_ou][download][type] = ""
projects[pathauto_ou][download][url] = ""
projects[pathauto_ou][type] = "module"
projects[pathauto_ou][subdir] = "custom/ou_features"
projects[pathauto_ou][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[permissions_ou][download][type] = ""
projects[permissions_ou][download][url] = ""
projects[permissions_ou][type] = "module"
projects[permissions_ou][subdir] = "custom/ou_features"
projects[permissions_ou][version] = "1.0"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.7"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.11"

projects[wysiwyg_filter][subdir] = "contrib"
projects[wysiwyg_filter][version] = "1.6-rc2"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[makingbritain][download][type] = ""
projects[makingbritain][download][url] = ""
projects[makingbritain][type] = "theme"
projects[makingbritain][version] = "(D7)"

projects[zen][version] = "5.5"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[edrm][download][type] = ""
projects[edrm][download][url] = ""
projects[edrm][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[migrate_ou_ips][download][type] = ""
projects[migrate_ou_ips][download][url] = ""
projects[migrate_ou_ips][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[nodewords_migrate][download][type] = ""
projects[nodewords_migrate][download][url] = ""
projects[nodewords_migrate][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_ams][download][type] = ""
projects[ou_ams][download][url] = ""
projects[ou_ams][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_profile][download][type] = ""
projects[ou_profile][download][url] = ""
projects[ou_profile][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[profile_client][download][type] = ""
projects[profile_client][download][url] = ""
projects[profile_client][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_rps][download][type] = ""
projects[ou_rps][download][url] = ""
projects[ou_rps][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[payments][download][type] = ""
projects[payments][download][url] = ""
projects[payments][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[admin][download][type] = ""
projects[admin][download][url] = ""
projects[admin][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[sams][download][type] = ""
projects[sams][download][url] = ""
projects[sams][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cvsl][download][type] = ""
projects[cvsl][download][url] = ""
projects[cvsl][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[enduringlove][download][type] = ""
projects[enduringlove][download][url] = ""
projects[enduringlove][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[heat][download][type] = ""
projects[heat][download][url] = ""
projects[heat][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[historyofou][download][type] = ""
projects[historyofou][download][url] = ""
projects[historyofou][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ido_home][download][type] = ""
projects[ido_home][download][url] = ""
projects[ido_home][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ido_main][download][type] = ""
projects[ido_main][download][url] = ""
projects[ido_main][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[living_multiculture][download][type] = ""
projects[living_multiculture][download][url] = ""
projects[living_multiculture][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[mulberry][download][type] = ""
projects[mulberry][download][url] = ""
projects[mulberry][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[oaa][download][type] = ""
projects[oaa][download][url] = ""
projects[oaa][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[openuniversity_edu][download][type] = ""
projects[openuniversity_edu][download][url] = ""
projects[openuniversity_edu][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_business_school][download][type] = ""
projects[ou_business_school][download][url] = ""
projects[ou_business_school][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_credit_transfer][download][type] = ""
projects[ou_credit_transfer][download][url] = ""
projects[ou_credit_transfer][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_creet][download][type] = ""
projects[ou_creet][download][url] = ""
projects[ou_creet][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_digitalframework][download][type] = ""
projects[ou_digitalframework][download][url] = ""
projects[ou_digitalframework][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_intranet][download][type] = ""
projects[ou_intranet][download][url] = ""
projects[ou_intranet][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_ioe][download][type] = ""
projects[ou_ioe][download][url] = ""
projects[ou_ioe][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_itunes][download][type] = ""
projects[ou_itunes][download][url] = ""
projects[ou_itunes][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_law][download][type] = ""
projects[ou_law][download][url] = ""
projects[ou_law][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_researchcentres_ccig][download][type] = ""
projects[ou_researchcentres_ccig][download][url] = ""
projects[ou_researchcentres_ccig][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_researchcentres_diasporas][download][type] = ""
projects[ou_researchcentres_diasporas][download][url] = ""
projects[ou_researchcentres_diasporas][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_researchcentres_herc][download][type] = ""
projects[ou_researchcentres_herc][download][url] = ""
projects[ou_researchcentres_herc][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_researchcentres_ikd][download][type] = ""
projects[ou_researchcentres_ikd][download][url] = ""
projects[ou_researchcentres_ikd][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_researchcentres_osrc][download][type] = ""
projects[ou_researchcentres_osrc][download][url] = ""
projects[ou_researchcentres_osrc][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_scienceresearch_cei][download][type] = ""
projects[ou_scienceresearch_cei][download][url] = ""
projects[ou_scienceresearch_cei][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ou_student_charter][download][type] = ""
projects[ou_student_charter][download][url] = ""
projects[ou_student_charter][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pufin][download][type] = ""
projects[pufin][download][url] = ""
projects[pufin][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tensions_and_prospects][download][type] = ""
projects[tensions_and_prospects][download][url] = ""
projects[tensions_and_prospects][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tessafricav2][download][type] = ""
projects[tessafricav2][download][url] = ""
projects[tessafricav2][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[unison][download][type] = ""
projects[unison][download][url] = ""
projects[unison][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[videofinder][download][type] = ""
projects[videofinder][download][url] = ""
projects[videofinder][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[vre][download][type] = ""
projects[vre][download][url] = ""
projects[vre][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[zen_ch_sub][download][type] = ""
projects[zen_ch_sub][download][url] = ""
projects[zen_ch_sub][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[PHPMailer][download][type] = ""
libraries[PHPMailer][download][url] = ""
libraries[PHPMailer][directory_name] = "PHPMailer"
libraries[PHPMailer][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[iCalcreator][download][type] = ""
libraries[iCalcreator][download][url] = ""
libraries[iCalcreator][directory_name] = "iCalcreator"
libraries[iCalcreator][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[mailchimp][download][type] = ""
libraries[mailchimp][download][url] = ""
libraries[mailchimp][directory_name] = "mailchimp"
libraries[mailchimp][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[htmlpurifier][download][type] = ""
libraries[htmlpurifier][download][url] = ""
libraries[htmlpurifier][directory_name] = "htmlpurifier"
libraries[htmlpurifier][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ARC2][download][type] = ""
libraries[ARC2][download][url] = ""
libraries[ARC2][directory_name] = "ARC2"
libraries[ARC2][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[arc2][download][type] = ""
libraries[arc2][download][url] = ""
libraries[arc2][directory_name] = "arc2"
libraries[arc2][type] = "library"

