; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.52"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.9"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.16"

projects[ckeditor_link][subdir] = "contrib"
projects[ckeditor_link][version] = "2.3"

projects[content_access][subdir] = "contrib"
projects[content_access][version] = "1.2-beta2"

projects[date][subdir] = "contrib"
projects[date][version] = "2.8"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[easy_breadcrumb][subdir] = "contrib"
projects[easy_breadcrumb][version] = "2.12"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.6"

projects[features][subdir] = "contrib"
projects[features][version] = "2.2"

projects[features_override][subdir] = "contrib"
projects[features_override][version] = "2.0-rc2"

projects[media][subdir] = "contrib"
projects[media][version] = "1.4"

projects[filefield_sources][subdir] = "contrib"
projects[filefield_sources][version] = "1.9"

projects[ftools][subdir] = "contrib"
projects[ftools][version] = "1.6"

projects[globalredirect][subdir] = "contrib"
projects[globalredirect][version] = "1.5"

projects[htmlpurifier][subdir] = "contrib"
projects[htmlpurifier][version] = "1.0"

projects[imce][version] = "1.9"

projects[imce_filefield][version] = "1.1"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.2"

projects[oembed][subdir] = "contrib"
projects[oembed][version] = "0.1-beta3"

projects[memcache_storage][subdir] = "contrib"
projects[memcache_storage][version] = "1.4"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.4"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.0-rc2"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0-alpha2"

projects[references][subdir] = "contrib"
projects[references][version] = "2.1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.7"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.11"

projects[wysiwyg_filter][subdir] = "contrib"
projects[wysiwyg_filter][version] = "1.6-rc2"

projects[zen][version] = "5.5"

